# -*- coding: utf-8 -*-
"""Predicting Song Popularity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDELtGZWp143TGnEX3oqn8JCvbfD1Hpl
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from google.colab import drive

# Load dataset
df = pd.read_csv("/content/drive/MyDrive/Predicting Song Popularity/dataset.csv")

# Target: popularity → binary
df['target'] = (df['popularity'] >= 50).astype(int)

# Features
features = ['danceability','energy','valence','tempo','loudness','acousticness','instrumentalness']
X = df[features].values
y = df['target'].values

# Normalize
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

class Perceptron:
    def __init__(self, lr=0.01, n_iter=1000):
        self.lr = lr
        self.n_iter = n_iter

    def fit(self, X, y):
        self.w = np.zeros(X.shape[1])
        self.b = 0
        for _ in range(self.n_iter):
            for xi, target in zip(X, y):
                update = self.lr * (target - self.predict(xi))
                self.w += update * xi
                self.b += update

    def net_input(self, X):
        return np.dot(X, self.w) + self.b

    def predict(self, X):
        return np.where(self.net_input(X) >= 0.0, 1, 0)

    def predict_proba(self, X):
        return self.predict(X).astype(float)

# Train
perc = Perceptron(lr=0.01, n_iter=10)
perc.fit(X_train, y_train)
y_pred_perc = perc.predict(X_test)
y_proba_perc = perc.predict_proba(X_test)
acc_perc = np.mean(y_pred_perc == y_test)
rmse_perc = np.sqrt(mean_squared_error(y_test, y_proba_perc))
print("Perceptron Accuracy:", acc_perc*100,"%")
print("RMSE Accuracy:", rmse_perc*100,"%")

class LogisticRegressionScratch:
    def __init__(self, lr=0.01, n_iter=1000):
        self.lr = lr
        self.n_iter = n_iter

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        self.w = np.zeros(X.shape[1])
        self.b = 0
        for _ in range(self.n_iter):
            linear = np.dot(X, self.w) + self.b
            y_pred = self.sigmoid(linear)
            dw = np.dot(X.T, (y_pred - y)) / len(y)
            db = np.sum(y_pred - y) / len(y)
            self.w -= self.lr * dw
            self.b -= self.lr * db

    def predict(self, X):
        linear = np.dot(X, self.w) + self.b
        return (self.sigmoid(linear) >= 0.5).astype(int)

    def predict_proba(self, X):
        linear = np.dot(X, self.w) + self.b
        return self.sigmoid(linear)

# Train
logreg = LogisticRegressionScratch(lr=0.001, n_iter=1000)
logreg.fit(X_train, y_train)
y_pred_log = logreg.predict(X_test)
y_proba_log = logreg.predict_proba(X_test)
acc_log = np.mean(y_pred_log == y_test)
rmse_log = np.sqrt(mean_squared_error(y_test, y_proba_log))
print("LogReg Accuracy:", acc_log*100,"%")
print("RMSE Accuracy:", rmse_log*100,"%")

class SimpleNN:
    def __init__(self, input_dim, hidden_dim=8, lr=0.01, n_iter=1000):
        self.lr = lr
        self.n_iter = n_iter
        self.W1 = np.random.randn(input_dim, hidden_dim) * 0.01
        self.b1 = np.zeros((1, hidden_dim))
        self.W2 = np.random.randn(hidden_dim, 1) * 0.01
        self.b2 = np.zeros((1, 1))

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def relu(self, z):
        return np.maximum(0, z)

    def relu_deriv(self, z):
        return (z > 0).astype(float)

    def fit(self, X, y):
        y = y.reshape(-1, 1)
        for _ in range(self.n_iter):
            # Forward
            Z1 = np.dot(X, self.W1) + self.b1
            A1 = self.relu(Z1)
            Z2 = np.dot(A1, self.W2) + self.b2
            A2 = self.sigmoid(Z2)

            # Backprop
            m = len(y)
            dZ2 = A2 - y
            dW2 = np.dot(A1.T, dZ2) / m
            db2 = np.sum(dZ2, axis=0, keepdims=True) / m
            dA1 = np.dot(dZ2, self.W2.T)
            dZ1 = dA1 * self.relu_deriv(Z1)
            dW1 = np.dot(X.T, dZ1) / m
            db1 = np.sum(dZ1, axis=0, keepdims=True) / m

            # Update
            self.W1 -= self.lr * dW1
            self.b1 -= self.lr * db1
            self.W2 -= self.lr * dW2
            self.b2 -= self.lr * db2

    def predict_proba(self, X):
        Z1 = np.dot(X, self.W1) + self.b1
        A1 = self.relu(Z1)
        Z2 = np.dot(A1, self.W2) + self.b2
        A2 = self.sigmoid(Z2)
        return A2.flatten()

    def predict(self, X):
        return (self.predict_proba(X) >= 0.5).astype(int)

        # Train
nn = SimpleNN(input_dim=X_train.shape[1], hidden_dim=8, lr=0.01, n_iter=2000)
nn.fit(X_train, y_train)
y_pred_nn = nn.predict(X_test)
y_proba_nn = nn.predict_proba(X_test)
acc_nn = np.mean(y_pred_nn == y_test)
rmse_nn = np.sqrt(mean_squared_error(y_test, y_proba_nn))
print("NN Accuracy:", acc_nn*100,"%")
print("RMSE Accuracy:", rmse_nn*100,"%")

results = pd.DataFrame({
    "Model": ["Perceptron", "Logistic Regression", "Neural Network"],
    "Accuracy": [acc_perc, acc_log, acc_nn],
    "RMSE": [rmse_perc, rmse_log, rmse_nn]
})

print(results)